<a href="https://colab.research.google.com/github/Kathi3/Simple-Random-Sampling/blob/main/Copy_of_Python_Programming_Simple_Random_Sampling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font color="green">To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.</font>

# Python Programming:  Simple Random Sampling


## Importing our Libraries

In [ ]:
# importing numpy
import numpy as np

# importing pandas
import pandas as pd

# importing random module
# we will use random.sample() function to return a k length 
# list of unique elements chosen from our population
import random

## 1.0 Selecting More than One item from a List

In [ ]:
# Example 1
# ---
# Selecting more than one item from a list 
# ---
#

list = [20, 40, 80, 100, 120]
print ("Choosing 3 random items from a list using sample function", random.sample(list, k=3))

list = [20, 40, 20, 20, 20]
print ("Choosing 3 random items from a list using sample function",random.sample(list, k=3))

# As you can see we pass k=3 to choose 3 random elements from a list. 
# In return, we got a list of 3 random items.

Choosing 3 random items from a list using sample function [80, 20, 100]
Choosing 3 random items from a list using sample function [20, 20, 20]


### <font color="green"> 1.0 Challenges</font>

In [ ]:
# Challenge 1
# ---
# Question: Create a list containing 10 counties in Kenya 
# then select 2 random counties from the list.
# ---
# 
list = ["Nairobi", "Kisii", "Kiambu", "Mombasa", "Nyali", "Kitui", "Machakos", "Nakuru", "Nyandarua", "Murang'a"]
print("Choosing 2 random counties based on the given list", random.sample(list, k=2))

Choosing 3 random counties ['Nakuru', "Murang'a"]


## 2.0  Selecting the Random Sample from Dictionary

In [ ]:
# Example 1
# ---
# We can select a random key-value pair from the dictionary as shown 
# ---
#
marks_dict = {
  "Kelly": 55,
  "jhon": 70,
  "Donald": 60,
  "Lennin" :50
}

print ("Choosing 2 random items from a dictionary using sample method ", random.sample(marks_dict.items(), k=2))

Choosing 2 random items from a dictionary using sample method  [('Donald', 60), ('Lennin', 50)]


### <font color="green">2.0 Challenges</font>

In [6]:
# Challenge 1
# ---
# A caterer offers three different food packages; 
# bronze package: starch:rice stew:chicken curry vegetable:cabbages desert:melon
# silver package: starch:rice and chappati  stew:beef curry vegetable:spinach desert:melon and bananas
# gold package: starch:rice, chappati and mukimo stew: beef curry vegetable:spinach and managu desert: tart
# Create a dictionary that stores the above information and select a sample of size 2 
# ---
#
caterer_dict = {
  
    'bronzepack' : {
        'starch': 'rice', 
        'stew': 'chicken curry', 
        'vegetable': 'cabbages', 
        'dessert': 'melon'
    },
    'silverpack': {
        'starch': 'rice and chapati', 
        'stew': 'beef curry', 
        'vegetable': 'spinach', 
        'dessert': 'melon and banana'
    },
    'goldpack' : {
        'starch': 'rice, chapati and mukimo', 
        'stew': 'beef curry', 
        'vegetable': 'spinach and managu', 
        'dessert': 'tart'
    }
}
print ("Choosing 2 random items from a dictionary using sample method ", random.sample(caterer_dict.items(), k=2))

Choosing 2 random items from a dictionary using sample method  [('goldpack', {'starch': 'rice, chapati and mukimo', 'stew': 'beef curry', 'vegetable': 'spinach and managu', 'dessert': 'tart'}), ('bronzepack', {'starch': 'rice', 'stew': 'chicken curry', 'vegetable': 'cabbages', 'dessert': 'melon'})]


## 3.0 Selecting a Random Sample with Replacement to including repetition


In [12]:
# Example 1
# ---
# We can select a random sample with replacement to include repetition as shown below
# ---
# 
names = ["Roger", "Nadal", "Novac", "Andre", "Sarena", "Mariya", "Martina"]

print("random sample with replacement to including repetition ", random.choices(names, k=3))

random sample with replacement to including repetition  ['Andre', 'Andre', 'Nadal']


### <font color="green">3.0 Challenges</font>

In [13]:
# Challenge 1
# ---
# Question: Select a random sample of 3 with replacement to include replacement from the 
# following list of months
# ---
#

months = ['January', 'February', 'March', 'April', 'May', 'June', 'July',
          'August', 'September', 'October', 'November', 'December']

print("RS with replacement, including repetition", random.choices(months, k = 3))

RS with replacement, including repetition ['November', 'March', 'January']


## 4.0 Selecting a Random Sample from a Range of Integers

In [14]:
# Example 1
# ---
# We can select a random sample from a range of integers as shown below
# ---
# 

weight_set = {40, 50, 55, 65, 75, 80}

print ("Choosing 4 random items from a set ", random.sample(weight_set, k=4))

Choosing 4 random items from a set  [75, 40, 65, 55]


### <font color="green">4.1 Challenges</font>

In [15]:
# Challenge 1
# ---
# Question: Select a random sample from a range of integers as shown below
# --- 
# 
weight_set = {4, 5, 6, 7, 8, 9, 10}

print("n =", random.sample(weight_set, k=4))

n = [5, 8, 6, 4]


## 5.0 Selecting a Sample Array from a Large multidimensional Array



In [16]:
# Example 1
# ---
# We can select a sample array from a large multidimensional array as shown
# ---
# 

array = np.array([[2 ,4, 6], [5, 10, 15], [6, 12, 18], [7, 14, 21], [8, 16, 24]]) 
print("Printing 2D Array")
print(array)

# selecting multiple random rows from the 2D as shown
print("Selecting multiple random rows from the 2D array")
randomRows = np.random.randint(5, size=2)
for i in randomRows:
  print(array[i,:])

Printing 2D Array
[[ 2  4  6]
 [ 5 10 15]
 [ 6 12 18]
 [ 7 14 21]
 [ 8 16 24]]
Selecting multiple random rows from the 2D array
[ 5 10 15]
[ 6 12 18]


### <font color="green">5.0 Challenges</font>

In [26]:
# Challenge 1
# ---
# Question: Select two arrays from the given multidimensional array
# ---
# 

array =np.array ([[2, 4, 6, 8, 10], [3, 6, 9, 12, 15], [4, 8, 12, 16, 20], [1 ,2 , 4, 5, 6], [5, 10, 15, 20, 25], [6, 12, 18, 24, 30], [7, 14, 21, 28, 35]] )

print("Printing A")
print(array)

print("Select Random Rows from the 2D")
randomRows = np.random.randint(4, size=4)
for i in randomRows:
  print(array[i, :])

Printing A
[[ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 1  2  4  5  6]
 [ 5 10 15 20 25]
 [ 6 12 18 24 30]
 [ 7 14 21 28 35]]
Select Random Rows from the 2D
[1 2 4 5 6]
[ 3  6  9 12 15]
[ 4  8 12 16 20]
[ 3  6  9 12 15]


## 6.0 Selecting Random Samples from a Dataset

In [27]:
# Example 1
# ---
# Selecting a random sample from the following medical appointments dataset
# ---
# Dataset url = http://bit.ly/MedicalAppointmentsDataset
# ---
# 

# Loading the dataset
medical_df = pd.read_csv("http://bit.ly/MedicalAppointmentsDataset")

# Determining the size
print(medical_df.shape)


# Previewing the dataset
print(medical_df.head())

# Selecting the sample 
medical_sample = medical_df.sample(n = 10, replace="False")
print(medical_sample)

(110527, 14)
      PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
0  2.987250e+13        5642903      F  ...       0            0       No
1  5.589978e+14        5642503      M  ...       0            0       No
2  4.262962e+12        5642549      F  ...       0            0       No
3  8.679512e+11        5642828      F  ...       0            0       No
4  8.841186e+12        5642494      F  ...       0            0       No

[5 rows x 14 columns]
           PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
86079   8.678819e+12        5577302      M  ...       0            1      Yes
52946   8.467648e+12        5725184      F  ...       0            0       No
108049  2.852923e+14        5759369      F  ...       0            0       No
48666   3.733844e+14        5617982      M  ...       0            0       No
74142   6.491812e+13        5623310      M  ...       0            0      Yes
61658   6.114673e+12        5680394      F  ...       0   

### <font color="green">6.0 Challenges </font>

In [28]:
# Challenge 1
# ---
# Select a random sample of 10 from the given dataset below 
# ---
# Dataset url = http://bit.ly/DSRussianInvestigation
# ---
#
RussianInv_df = pd.read_csv("http://bit.ly/DSRussianInvestigation")
print(RussianInv_df.shape)
print(RussianInv_df.head())
RussianInv_Sample= RussianInv_df.sample(n = 10, replace="False")

print(RussianInv_Sample)

(194, 13)
  investigation investigation-start  ... american      president
0     watergate          1973-05-19  ...     True  Richard Nixon
1     watergate          1973-05-19  ...     True  Richard Nixon
2     watergate          1973-05-19  ...     True  Richard Nixon
3     watergate          1973-05-19  ...     True  Richard Nixon
4     watergate          1973-05-19  ...     True  Richard Nixon

[5 rows x 13 columns]
    investigation investigation-start  ... american         president
65      watergate          1973-05-19  ...     True     Richard Nixon
174        russia          2017-05-17  ...    False      Donald Trump
68      watergate          1973-05-19  ...     True     Richard Nixon
149      cisneros          1995-05-24  ...     True      Bill Clinton
92    iran-contra          1986-12-19  ...     True     Ronald Reagan
70      watergate          1973-05-19  ...     True     Richard Nixon
129    whitewater          1994-08-05  ...     True      Bill Clinton
41      watergate

In [31]:
# Challenge 2
# ---
# A medical company would like to follow up with 50 patients who never showed up for appointments 
# but received an sms. Select a random sample from such patients given the medical dataset below 
# ---
# Dataset url = http://bit.ly/MedicalAppointmentsDataset
# ---
#
MedicalApp_df = pd.read_csv("http://bit.ly/MedicalAppointmentsDataset")
print(MedicalApp_df.shape)
print(MedicalApp_df.head())
MedicalApp_Sample= RussianInv_df.sample(n = 12, replace="False")

print(MedicalApp_Sample)

(110527, 14)
      PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
0  2.987250e+13        5642903      F  ...       0            0       No
1  5.589978e+14        5642503      M  ...       0            0       No
2  4.262962e+12        5642549      F  ...       0            0       No
3  8.679512e+11        5642828      F  ...       0            0       No
4  8.841186e+12        5642494      F  ...       0            0       No

[5 rows x 14 columns]
    investigation investigation-start  ... american      president
46      watergate          1973-05-19  ...     True  Richard Nixon
1       watergate          1973-05-19  ...     True  Richard Nixon
44      watergate          1973-05-19  ...     True  Richard Nixon
52      watergate          1973-05-19  ...     True  Richard Nixon
44      watergate          1973-05-19  ...     True  Richard Nixon
75    edwin-meese          1984-04-02  ...     True  Ronald Reagan
135          espy          1994-09-09  ...     True   Bil